version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - H2_CONSOLE_ENABLED=true
    volumes:
      - ./logs:/app/logs
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge