spring:
  application:
    name: course-management-system

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console

  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: ${PORT:8080}

logging:
  level:
    com.university.course_management_system: INFO