spring:
  profiles:
    active: docker
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

server:
  port: ${PORT:8080}

logging:
  level:
    com.university.course_management_system: INFO
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized